[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.125.4"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_BASEURL = "https://ortabels.netlify.app/"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
